insert into linkgroup(user_id, group_name) values(1 ,  "Javascript");
insert into linkgroup(user_id, group_name) values(2 ,  "Android links from Buffer");
insert into linkgroup(user_id, group_name) values(3 ,  "jQuery-Plugins");
insert into linkgroup(user_id, group_name) values(4 ,  "iOS Tools & 3rd party services");
insert into linkgroup(user_id, group_name) values(2 ,  "Android links from Buffer");
insert into linkgroup(user_id, group_name) values(5 ,  "Entrepreneurship");
insert into linkgroup(user_id, group_name) values(6 ,  "Kippt API");
insert into linkgroup(user_id, group_name) values(7 ,  "Flight");
insert into linkgroup(user_id, group_name) values(8 ,  "Web Related Podcasts");
insert into linkgroup(user_id, group_name) values(9 ,  "Business & Management");
insert into linkgroup(user_id, group_name) values(10,  "Good Long Reads");
insert into linkgroup(user_id, group_name) values(11,  "Crème de la crema");
insert into linkgroup(user_id, group_name) values(12,  "Productivity");
insert into linkgroup(user_id, group_name) values(13,  "JS online tools");
insert into linkgroup(user_id, group_name) values(14,  "Good Long Reads");
insert into linkgroup(user_id, group_name) values(15,  "Exploring our universe");
insert into linkgroup(user_id, group_name) values(16,  "Design");
insert into linkgroup(user_id, group_name) values(17,  "Free Location Datasets");
insert into linkgroup(user_id, group_name) values(18,  "Handy bits");
insert into linkgroup(user_id, group_name) values(19,  "Python");
insert into linkgroup(user_id, group_name) values(20,  "Productivity");
