insert into link(title,url,url_domain,description,updated,group_id) values("Video: Throwing and catching an inverted pendulum  with quadrocopters | Robohub","http://robohub.org/video-throwing-and-catching-an-inverted-pendulum-with-quadrocopters/","robohub.org","","2013-02-21T23:44:25",7);
insert into link(title,url,url_domain,description,updated,group_id) values("Matternet","http://matternet.us/","matternet.us","","2013-01-20T16:37:31",7);
insert into link(title,url,url_domain,description,updated,group_id) values("How CoolChip Got $500K from Peter Thiel's Founders Fund: A Salsa Story | Xconomy","http://www.xconomy.com/boston/2012/04/25/how-coolchip-got-500k-from-peter-thiels-founders-fund-a-salsa-story/2/","www.xconomy.com","","2013-01-11T12:14:46",7);
insert into link(title,url,url_domain,description,updated,group_id) values("DARPA/Boeing DiscRotor - YouTube","http://www.youtube.com/watch?v=pg6LuwyNIxk","www.youtube.com","","2012-12-08T15:32:22",7);
insert into link(title,url,url_domain,description,updated,group_id) values("BBC Nature - Hummingbirds' backward flight is efficient","http://www.bbc.co.uk/nature/19731176","www.bbc.co.uk","","2012-09-28T13:57:52",7);
insert into link(title,url,url_domain,description,updated,group_id) values("Ionocraft - Wikipedia, the free encyclopedia","http://en.wikipedia.org/wiki/Ionocraft","en.wikipedia.org","","2012-09-03T19:55:52",7);
insert into link(title,url,url_domain,description,updated,group_id) values("DXmicro-M4 Smallest Dragonfly Ornithopter? - YouTube","http://www.youtube.com/watch?v=RaaBkl96JN4&feature=related","www.youtube.com","","2012-09-02T16:57:06",7);
insert into link(title,url,url_domain,description,updated,group_id) values("Ornicopter - YouTube","http://www.youtube.com/watch?v=0Z2Rr39hiUs","www.youtube.com","","2012-09-02T16:52:22",7);
insert into link(title,url,url_domain,description,updated,group_id) values("Gamera II hits new high with unofficial human-powered helicopter altitude record (video) -- Engadget","http://www.engadget.com/2012/08/29/gamera-ii-human-helicopter-unofficial-record/","www.engadget.com","","2012-09-02T16:31:33",7);
