insert into link(title,url,url_domain,description,updated,group_id) values("repl.it","http://repl.it/","repl.it","","2012-04-09T12:02:39",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Tinker  Social Code Collaboration","https://tinker.io/","tinker.io","","2012-03-08T13:08:18",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Online JavaScript beautifier","http://jsbeautifier.org/","jsbeautifier.org","","2012-03-08T12:58:59",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Plunker - Editor","http://plunker.no.de/edit","plunker.no.de","","2012-03-08T12:17:59",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Scriptular","http://scriptular.com/","scriptular.com","","2012-03-05T12:33:54",13);
insert into link(title,url,url_domain,description,updated,group_id) values("PimpMyJS - Your minified or pretty printed JavaScript","http://pimpmyjs.com/","pimpmyjs.com","","2012-02-02T12:04:15",13);
insert into link(title,url,url_domain,description,updated,group_id) values("JavaScript Comparisons Using jQuery, Dojo, MooTools, Prototype, etc.","http://paralleljs.com/","paralleljs.com","","2012-02-02T12:03:44",13);
insert into link(title,url,url_domain,description,updated,group_id) values("jQuery google api and other google hosted javascript libraries. - ScriptSrc.net","http://scriptsrc.net/","scriptsrc.net","","2012-02-02T11:59:50",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Closure Compiler Service","http://closure-compiler.appspot.com/home","closure-compiler.appspot.com","","2012-02-02T11:59:34",13);
insert into link(title,url,url_domain,description,updated,group_id) values("Online YUI Compressor","http://refresh-sf.com/yui/","refresh-sf.com","","2012-02-02T11:58:49",13);
insert into link(title,url,url_domain,description,updated,group_id) values("jsPerf: JavaScript performance playground","http://jsperf.com/","jsperf.com","","2012-02-02T11:57:00",13);
insert into link(title,url,url_domain,description,updated,group_id) values("JavaScript console - for debugging JavaScript and remote debugging mobile web apps","http://jsconsole.com/","jsconsole.com","","2012-02-02T11:56:36",13);
insert into link(title,url,url_domain,description,updated,group_id) values("JS Bin - Collaborative JavaScript Debugging","http://jsbin.com/","jsbin.com","","2012-02-02T11:56:09",13);
insert into link(title,url,url_domain,description,updated,group_id) values("URL Decoder/Encoder","http://meyerweb.com/eric/tools/dencoder/","meyerweb.com","","2012-02-02T11:53:43",13);
insert into link(title,url,url_domain,description,updated,group_id) values("slayeroffice | key code tool","http://slayeroffice.com/tools/keycode/","slayeroffice.com","","2012-02-02T11:52:41",13);
