insert into link(title,url,url_domain,description,updated,group_id) values("2010 Census TIGER/Line Shapefiles Main Page - Geography - US Census Bureau","https://www.census.gov/geo/www/tiger/tgrshp2010/tgrshp2010.html","www.census.gov","","2012-09-12T21:55:34",17);
insert into link(title,url,url_domain,description,updated,group_id) values("GEOFABRIK Download Area","http://download.geofabrik.de/osm/","download.geofabrik.de","","2012-08-11T01:50:20",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Natural Earth","http://www.naturalearthdata.com/","www.naturalearthdata.com","","2012-08-10T23:34:02",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Cal-Atlas Download","http://atlas.ca.gov/download.html","atlas.ca.gov","","2012-07-11T00:24:43",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Spatial Information Library Home Page","http://dpw.lacounty.gov/general/spatiallibrary/index.cfm?agree=agree","dpw.lacounty.gov","","2012-07-11T00:22:24",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Metro Extracts","http://metro.teczno.com/","metro.teczno.com","","2012-07-10T23:52:15",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Data Dashboard","http://www.cityofboston.gov/doit/databoston/app/data.aspx","www.cityofboston.gov","","2012-07-10T23:51:28",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Open Data | Los Angeles County Enterprise GIS","http://egis3.lacounty.gov/eGIS/tag/open-data/","egis3.lacounty.gov","","2012-07-10T23:37:49",17);
insert into link(title,url,url_domain,description,updated,group_id) values("NYC Open Data","https://nycopendata.socrata.com/","nycopendata.socrata.com","","2012-07-10T23:36:58",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Data | San Francisco","https://data.sfgov.org/","data.sfgov.org","","2012-07-10T23:36:23",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Free GIS Datasets - Categorised List","http://freegisdata.rtwilson.com/","freegisdata.rtwilson.com","","2012-07-10T23:35:45",17);
insert into link(title,url,url_domain,description,updated,group_id) values("Data | ACLED","http://www.acleddata.com/data/","www.acleddata.com","","2012-07-10T23:34:52",17);
