 insert into user(username,email,password) values("jg",  "jg@example.com"  ,"123");     
 insert into user(username,email,password) values("joel",    "joel@example.com"    ,"123");     
 insert into user(username,email,password) values("WebOlymp",    "WebOlymp@example.com"    ,"123");     
 insert into user(username,email,password) values("claytonnarcis",   "claytonnarcis@example.com"   ,"123");     
 insert into user(username,email,password) values("woodlandalyssa",  "woodlandalyssa@example.com"  ,"123");     
 insert into user(username,email,password) values("karrisaarinen",   "karrisaarinen@example.com"   ,"123");     
 insert into user(username,email,password) values("judegomila",  "judegomila@example.com"  ,"123");     
 insert into user(username,email,password) values("akmur",   "akmur@example.com"   ,"123");     
 insert into user(username,email,password) values("woodlandal",  "woodlandal@example.com"  ,"123");     
 insert into user(username,email,password) values("tuutipiippo", "tuutipiippo@example.com" ,"123");     
 insert into user(username,email,password) values("vsaarinen",  "vsaarinen@example.com "  ,"123");     
 insert into user(username,email,password) values("leowid",  "leowid@example.com"  ,"123");     
 insert into user(username,email,password) values("codylindley", "codylindley@example.com" ,"123");     
 insert into user(username,email,password) values("tuutipiip" ,  "tuutipiip@example.com"   ,"123");     
 insert into user(username,email,password) values("robertgaal",  "robertgaal@example.com"  ,"123");     
 insert into user(username,email,password) values("kaitsu" , "kaitsu@example.com"  ,"123");     
 insert into user(username,email,password) values("tsharju","tsharju@example.com" ,"123");     
 insert into user(username,email,password) values("luke",    "luke@example.com"    ,"123");     
 insert into user(username,email,password) values("kennethreitz", "kennethreitz@example.com"    ,"123");     
 insert into user(username,email,password) values("leowid23" ,   "leowid23@example.com"    ,"123");     
